FROM python:3.11-slim

WORKDIR /app

COPY requirements/requirements-local.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ml/ /app/ml/

CMD ["python", "ml/data/generate_local_sample.py"]
